# Setup
title:               Alex's Memory Palace
tagline:             ''
description:         ''
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Alex James
  url:               https://twitter.com/mdo
  email:             <aj>@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
